require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'Truckr' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])
  
  pod 'GoogleMaps'
  pod 'Google-Maps-iOS-Utils'

  target 'TruckrTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)

    installer.pods_project.targets.each do |target|
       if target.name == 'react-native-google-maps'
          target.build_configurations.each do |config|
          config.build_settings['CLANG_ENABLE_MODULES'] = 'No'
       end
    end
       if target.name == "React"
         target.remove_from_project
       end
    end
  end
  
  
end
